// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Random = require("bs-platform/lib/js/random.js");
var MainView = require("./MainView.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var RestaurantCard = require("./RestaurantCard.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");

var restaurants = /* :: */[
  /* record */[
    /* name */"Caf\xc3\xa9 \xc3\x81rabe",
    /* lat */-23.5744987,
    /* lng */-46.690489,
    /* cuisine : Arab */1
  ],
  /* :: */[
    /* record */[
      /* name */"Giggio",
      /* lat */-23.5653385,
      /* lng */-46.6836678,
      /* cuisine : Italian */0
    ],
    /* :: */[
      /* record */[
        /* name */"Paulinhos Grill",
        /* lat */0.0,
        /* lng */0.0,
        /* cuisine : Brazilian */2
      ],
      /* :: */[
        /* record */[
          /* name */"Landi",
          /* lat */0.0,
          /* lng */0.0,
          /* cuisine : Brazilian */2
        ],
        /* :: */[
          /* record */[
            /* name */"Alem\xc3\xa3o",
            /* lat */-27.5744987,
            /* lng */-46.690489,
            /* cuisine : Other */3
          ],
          /* [] */0
        ]
      ]
    ]
  ]
];

function app() {
  Random.init(Date.now() | 0);
  List.mapi((function (i, r) {
          return ReasonReact.element(String(i), undefined, RestaurantCard.make(r, /* array */[]));
        }), restaurants);
  return ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                            Style$BsReactNative.flex(1),
                            /* :: */[
                              Style$BsReactNative.justifyContent(/* Center */2),
                              /* :: */[
                                Style$BsReactNative.alignItems(/* Center */2),
                                /* [] */0
                              ]
                            ]
                          ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, MainView.make(restaurants, /* array */[]))]));
}

exports.restaurants = restaurants;
exports.app = app;
/* MainView Not a pure module */
