// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Marker = require("./Marker.js");
var Random = require("bs-platform/lib/js/random.js");
var MapView = require("./MapView.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Text$BsReactNative = require("bs-react-native/lib/js/src/components/text.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var Button$BsReactNative = require("bs-react-native/lib/js/src/components/button.js");

var component = ReasonReact.reducerComponent("MainView");

function make(restaurants, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              console.log(self[/* state */1][/* restaurant */1]);
              var match = self[/* state */1][/* restaurant */1];
              var tmp;
              if (match !== undefined) {
                var r = match;
                var regiao = {
                  latitude: r[/* lat */1],
                  longitude: r[/* lng */2],
                  latitudeDelta: 0.09,
                  longitudeDelta: 0.04
                };
                tmp = ReasonReact.element(undefined, undefined, MapView.make(regiao, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                  Style$BsReactNative.width(/* Pt */Block.__(0, [400])),
                                  /* :: */[
                                    Style$BsReactNative.height(/* Pt */Block.__(0, [400])),
                                    /* [] */0
                                  ]
                                ])), /* array */[ReasonReact.element(undefined, undefined, Marker.make(regiao, undefined, /* array */[]))]));
              } else {
                tmp = ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "Escolha o restaurante", /* array */[]));
              }
              return ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(Style$BsReactNative.style(/* :: */[
                                        Style$BsReactNative.flex(1),
                                        /* :: */[
                                          Style$BsReactNative.justifyContent(/* Center */2),
                                          /* :: */[
                                            Style$BsReactNative.alignItems(/* Center */2),
                                            /* [] */0
                                          ]
                                        ]
                                      ])), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                              ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "Reason é da hora!", /* array */[])),
                              tmp,
                              ReasonReact.element(undefined, undefined, Button$BsReactNative.make(undefined, undefined, undefined, (function () {
                                            return Curry._1(self[/* send */3], /* Click */0);
                                          }), undefined, "Escolher restaurante")(/* array */[]))
                            ]));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* restaurants */restaurants,
                      /* restaurant */undefined
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (_, state) {
              return /* Update */Block.__(0, [/* record */[
                          /* restaurants */state[/* restaurants */0],
                          /* restaurant */List.nth(state[/* restaurants */0], Random.$$int(List.length(state[/* restaurants */0])))
                        ]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
