// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var marker = ( require('expo').MapView.Marker );

function make(coordinate, style, children) {
  return ReasonReact.wrapJsForReason(marker, {
              coordinate: coordinate,
              style: style
            }, children);
}

exports.marker = marker;
exports.make = make;
/* marker Not a pure module */
